"""Validated hardware and model configuration for the K230 gimbal app."""

BUILD_ID = "k230-h-vision-fast-r1"

PROJECT_DEVICE_DIR = "/sdcard/K230_GIMBAL"
KMODEL_PATH = "/data/best.kmodel"
LABELS_PATH = "/data/labels.txt"

SENSOR_ID = 2
DISPLAY_DRIVER = "ST7701"
DISPLAY_WIDTH = 800
DISPLAY_HEIGHT = 480
DISPLAY_TO_IDE = False

AI_WIDTH = 640
AI_HEIGHT = 384
MODEL_INPUT_SIZE = (320, 320)

ENABLE_FIXED_FOCUS = True
FIXED_FOCUS_POS = 210

TARGET_COORD_WIDTH = 400
TARGET_COORD_HEIGHT = 240

# Chassis radio stays dormant while the independent gimbal is brought up.
CHASSIS_RADIO_ENABLED = False
CHASSIS_WIFI_SSID = "CAR-K230"
CHASSIS_WIFI_PASSWORD = "K230CAR2026"
CHASSIS_RADIO_HOST = "192.168.4.1"
CHASSIS_RADIO_REMOTE_PORT = 4210
CHASSIS_RADIO_LOCAL_PORT = 4211
CHASSIS_RADIO_HEARTBEAT_MS = 250
CHASSIS_RADIO_HELLO_MS = 1000
CHASSIS_RADIO_OFFLINE_MS = 1000
CHASSIS_RADIO_RECONNECT_MS = 5000
CHASSIS_RADIO_PEER_RECOVER_MS = 5000

# H uses one expected steel ball. Low-confidence measurements still need
# spatial continuity; threshold changes are not the only dropout defense.
CONFIDENCE_THRESHOLD = 0.18
TARGET_ACQUIRE_CONFIDENCE = 0.35
TARGET_HOLD_CONFIDENCE = 0.18
TARGET_MATCH_MAX_DISTANCE_PX = 180
TARGET_FORGET_MS = 500
TARGET_COAST_MS = 120
TARGET_MAX_COAST_FRAMES = 2
NMS_THRESHOLD = 0.45
PRE_NMS_TOPK = 25
MAX_BOXES = 5
# The active H model has one class and one physical target, so scanning and NMS
# over every candidate is unnecessary. Explicit per-20-frame GC caused the
# measured 120 ms periodic control stalls; the fast path is allocation-bounded
# and is endurance-tested with scheduled GC disabled.
SINGLE_TARGET_FAST_PATH = True
GC_EVERY_N_FRAMES = 0
STATUS_PRINT_MS = 2000

BOX_COLOR = (0, 255, 0)
TEXT_COLOR = (0, 255, 0)
FPS_COLOR = (255, 255, 0)
FOCUS_COLOR = (255, 255, 0)
HUD_INFO_COLOR = (255, 255, 255)
HUD_GOOD_COLOR = (0, 255, 0)
HUD_WARN_COLOR = (255, 210, 0)
HUD_BAD_COLOR = (255, 64, 64)
HUD_UPDATE_MS = 100
OVERLAY_UPDATE_MS = 50

# H transition default: power-on runs camera detection only. The former
# two-axis tracker must not move hardware; H later enables only the beam axis
# through its own supervised controller.
CAN_ENABLED = False
GIMBAL_MOTION_ENABLED = False
GIMBAL_YAW_CAN_ADDRESS = 1
GIMBAL_PITCH_CAN_ADDRESS = 2
GIMBAL_YAW_POSITIVE_DIRECTION = "CW"
GIMBAL_PITCH_POSITIVE_DIRECTION = "UP"
GIMBAL_YAW_CONTINUOUS = True
GIMBAL_PITCH_CONTINUOUS = True
GIMBAL_YAW_CENTER_DEG = None
GIMBAL_PITCH_CENTER_DEG = None
# Reusable position-mode API bounds; ignored while both axes are continuous.
GIMBAL_YAW_SESSION_MIN_DEG = -180.0
GIMBAL_YAW_SESSION_MAX_DEG = 180.0
GIMBAL_PITCH_SESSION_MIN_DEG = -32.0
GIMBAL_PITCH_SESSION_MAX_DEG = 22.0
GIMBAL_YAW_MAX_RPM = 12.0
GIMBAL_PITCH_MAX_RPM = 8.0
GIMBAL_COMMAND_LEASE_MS = 600
GIMBAL_FEEDBACK_POLL_MS = 50
GIMBAL_VOLTAGE_POLL_MS = 500
GIMBAL_POSITION_TOLERANCE_DEG = 1.5
GIMBAL_RECOVERY_YAW_MIN_DEG = -200.0
GIMBAL_RECOVERY_YAW_MAX_DEG = 200.0
GIMBAL_RECOVERY_PITCH_MIN_DEG = -35.0
GIMBAL_RECOVERY_PITCH_MAX_DEG = 25.0
GIMBAL_RECOVERY_YAW_RPM = 4.0
GIMBAL_RECOVERY_PITCH_RPM = 3.5
GIMBAL_RECOVERY_LEASE_MS = 2000

TRACKING_DEADBAND_X = 12
TRACKING_DEADBAND_Y = 10
TRACKING_DEADBAND_HYSTERESIS_X = 4
TRACKING_DEADBAND_HYSTERESIS_Y = 3
# The installed camera X axis is opposite to positive Yaw.
TRACKING_YAW_RPM_PER_PIXEL = -0.135
# A positive Pitch command moves the target upward in the camera image.
TRACKING_PITCH_RPM_PER_PIXEL = -0.090
TRACKING_FILTER_ALPHA = 0.68
TRACKING_UPDATE_MS = 40
TRACKING_MISSING_STOP_MS = 120
TRACKING_LOST_TIMEOUT_MS = 500
TRACKING_MIN_YAW_RPM = 1.0
TRACKING_MIN_PITCH_RPM = 2.0
TRACKING_MAX_YAW_RPM = 11.0
TRACKING_MAX_PITCH_RPM = 7.0
TRACKING_YAW_ACCELERATION_RPM_S = 300
TRACKING_PITCH_ACCELERATION = 40
TRACKING_SPEED_CHANGE_RPM = 0.2
TRACKING_COMMAND_REFRESH_MS = 150
TRACKING_COMMAND_LEASE_MS = 600

# Reserved for K2. The selected MCP2515 + SN65HVD230 module uses an 8 MHz clock.
MCP2515_OSC_HZ = 8_000_000
CAN_BITRATE = 500_000
MCP2515_SCK_PIN = 15
MCP2515_MOSI_PIN = 16
MCP2515_MISO_PIN = 17
MCP2515_CS_PIN = 14
MCP2515_INT_PIN = 19
MCP2515_SPI_BAUDRATE = 5_000_000
MCP2515_SELF_TEST_ROUNDS = 4

# K3 sends only function 0x36 once per address, then returns to listen-only.
ZDT_DISCOVERY_ENABLED = True
ZDT_DISCOVERY_ADDRESSES = (1, 2)
ZDT_DISCOVERY_TIMEOUT_MS = 150
