[platformio]
default_envs = esp32c3

[env:esp32c3]
platform = espressif32@7.0.1
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_unflags =
    -O2
    -O3
build_flags =
    -Os
    -ffunction-sections
    -fdata-sections
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
